name: Check if a PR is good

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type-check
        run: tsc --noEmit

      # Add testing later
